import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>  
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.center}>
          <h1>Hunting Coder</h1>
        </div>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to lear JS in 2024</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
              voluptas.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to lear JS in 2024</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
              voluptas.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to lear JS in 2024</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
              voluptas.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to lear JS in 2024</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,
              voluptas.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
